MoodyCanvas/Moody/urls.py
from django.urls import path, include

from . import views

app_name = 'Moody'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('customers/', views.CustomersView.as_view(), name='customers'),
    path('new_cust/', views.new_cust, name='new_cust'),
    path('save_new_cust/', views.save_new_cust, name='save_new_cust'),
    path('<str:custname>/', views.PlatesView.as_view(), name='plates'),
    path('<str:custname>/new_plate/', views.new_plate, name='new_plate'),
    path('<str:custname>/save_new_plate/', views.save_new_plate, name='save_new_plate'),
    path('<str:custname>/<str:id_no>/', views.VerifsView.as_view(), name='verifs'),
    path('<str:custname>/<str:id_no>/new_verif/', views.NewVerifView.as_view(), name='new_verif'),
    path('<str:custname>/<str:id_no>/save_new_verif/', views.save_new_verif, name='save_new_verif'),
    path('<str:custname>/<str:id_no>/<str:ver_id>/', views.SummaryView.as_view(), name='summary'),
    path('<str:custname>/<str:id_no>/<str:ver_id>/map', views.CanvasView.as_view(), name='canvas'),
    path('<str:custname>/<str:id_no>/<str:ver_id>/heights', views.HeightsView.as_view(), name='heights'),
]

MoodyCanvas/Moody/models.py
from django.db import models


class Customer(models.Model):
    cust_name = models.CharField(max_length=50)

    def __str__(self):
        return self.cust_name

class Plate(models.Model):
    cust_id = models.ForeignKey(Customer, on_delete=models.CASCADE)
    plate_id = models.CharField(max_length=50)
    plate_sn = models.CharField(max_length=50)
    plate_mfr = models.CharField(max_length=50)
    plate_wid = models.IntegerField()
    plate_len = models.IntegerField()
    
    def __str__(self):
        return self.plate_id

class Verif(models.Model):
    plate_id = models.ForeignKey(Plate, on_delete=models.CASCADE)
    verif_date = models.DateTimeField('date performed')
    verif_foot = models.IntegerField()
    verif_north = models.IntegerField(default=4)
    verif_NS = models.IntegerField()
    verif_EW = models.IntegerField()
    verif_top = models.FloatField()
    verif_bot = models.FloatField()
    verif_start = models.FloatField()
    verif_end = models.FloatField()
    verif_rep = models.IntegerField()
    verif_flat = models.IntegerField()
    verif_grade = models.CharField(max_length=4)
    verif_len = models.IntegerField()
    verif_wid = models.IntegerField()
    verif_diag = models.IntegerField()
    clos_7 = models.IntegerField()
    clos_8 = models.IntegerField()
    verif_cert = models.TextField(max_length=50)
    verif_tech = models.TextField(max_length=50)
    verif_descr = models.TextField(max_length=50)
    verif_min = models.IntegerField()
    verif_max = models.IntegerField()

    def __str__(self):
        return str(self.verif_date.date())

class Profile(models.Model):
    verif_id = models.ForeignKey(Verif, on_delete=models.CASCADE)
    profile_id = models.IntegerField()

    def __str__(self):
        return str(self.profile_id)

class Meas(models.Model):
    verif_id = models.ForeignKey(Verif, on_delete=models.CASCADE)
    profile_id = models.ForeignKey(Profile, on_delete=models.CASCADE)
    measurement = models.FloatField()

    def __str__(self):
        return str(self.id) + ': ' + str(self.measurement)
    


MoodyCanvas/Moody/templates/Moody/customers.html
<!DOCTYPE html>
<html>
<head>
    <title>Moody Canvas!</title>

    <style>
        <!--
        body {
            color: #333;
            background-color: #ddd;
            text-align: center;
            vertical-align: middle;
            font-family: sans-serif;
            font-size: 14px;
        }

        h1 {
            font-family: Courier New, Courier, monospace;
            font-size: 28pt;
        }

        a, a:visited, a:active {
            color: #500;
            text-decoration: none;
        }

            a:hover {
                text-decoration: underline;
            }

        ul, li {
            list-style-type: none;
            list-style-position: inside;
            padding: 0;
            margin: 0;
        }

        #footer {
            right: 0;
            left: 0;
            text-align: center;
            font-family: Courier New, Courier, monospace;
            font-size: 12px;
            padding-bottom: 5px;
            margin-top: 20px;
        }

        #nav {
            list-style-type: none;
            display: inline-block;
            margin: 0 auto;
        }

            #nav li {
                list-style-type: none;
                display: inline-block;
            }

        #header {
            position: relative;
            display: inline-block;
            margin: 0 auto;
            text-align: center;
            width: 60%;
            border-bottom: 1px solid #444;
        }
        -->
    </style>
</head>
<body>
    <div id="header">
        <ul id="nav">
            <li><a href="{% url 'home:index' %}" style="font-size: 18px; font-family: Courier New, Courier, monospace; margin-right: 50px;">Moody Canvas!</a></li>
            <li><a rel="dead placeholder link">Procedure</a> &raquo;</li>
            <li><a href="{% url 'Moody:index' %}">Home</a>{% if user.is_authenticated %} &raquo;</li>
            <li><a href="{% url 'logout' %}">Logout</a>{% endif %}</li>
        </ul>
    </div>

    <h2>Customers</h2>
{% if user.is_authenticated %}
    <p><a href="{% url 'Moody:new_cust' %}">Add a New Customer</a></p>
{% endif %}
    {% if customer_list %}
    <p>View Plates For:</p>
    <ul>
        {% for c in customer_list %}
        <li><a href="{% url 'Moody:plates' c %}">{{ c }}</a></li>
        {% endfor %}
    </ul>
    {% endif %}
</body>
</html>

MoodyCanvas/Moody/templates/Moody/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Moody Canvas!</title>

    <style>
        <!--
        body {
            color: #333;
            background-color: #ddd;
            text-align: center;
            vertical-align: middle;
            font-family: sans-serif;
            font-size: 14px;
        }

        h1 {
            font-family: Courier New, Courier, monospace;
            font-size: 28pt;
        }

        a, a:visited, a:active {
            color: #500;
            text-decoration: none;
        }

            a:hover {
                text-decoration: underline;
            }

        ul, li {
            list-style-type: none;
            list-style-position: inside;
            padding: 0;
            margin: 0;
        }

        #footer {
            right: 0;
            left: 0;
            text-align: center;
            font-family: Courier New, Courier, monospace;
            font-size: 12px;
            padding-bottom: 5px;
            margin-top: 20px;
        }

        #nav {
            list-style-type: none;
            display: inline-block;
            margin: 0 auto;
        }

            #nav li {
                list-style-type: none;
                display: inline-block;
            }

        #header {
            position: relative;
            display: inline-block;
            margin: 0 auto;
            text-align: center;
            width: 60%;
            border-bottom: 1px solid #444;
        }
        -->
    </style>
</head>
<body>
    <div id="header">
        <ul id="nav">
            <li><a href="{% url 'home:index' %}" style="font-size: 18px; font-family: Courier New, Courier, monospace; margin-right: 50px;">Moody Canvas!</a></li>
            <li><a rel="dead placeholder link">Procedure</a>{% if user.is_authenticated %} &raquo;</li>
            <li><a href="{% url 'logout' %}">Logout</a>{% endif %}</li>
        </ul>
    </div>

    <p>
        <ul>
            <li style="padding-bottom: 15px; font-weight: bold;"><a href="{% url 'Moody:customers' %}">Enter Database (Browse by Customer)</a></li>
{% if user.is_authenticated %}
            <li><a href="{% url 'Moody:new_cust' %}">Add a Customer</a></li>
{% endif %}
        </ul>
    </p>

    {% if recent_verifs %}
    <h2>Last Few Verifications</h2>
    <ul>
        {% for v in recent_verifs %}
        <li><a href="{% url 'Moody:summary' v.plate_id.cust_id v.plate_id v.id %}">{{ v }}</a>: <a href="{% url 'Moody:verifs' v.plate_id.cust_id v.plate_id %}">{{ v.plate_id }}</a> @ <a href="{% url 'Moody:plates' v.plate_id.cust_id %}">{{ v.plate_id.cust_id }}</a>: {{ v.verif_descr }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</body>
</html>

MoodyCanvas/Moody/templates/Moody/new_cust.html
<!DOCTYPE html>
<html>
<head>
    <title>Moody Canvas!</title>
    <script>
        <!--
        function validateName() {
            var input_check = document.getElementById('custname');
            if (input_check.value == '') {
                alert("Be sure the only possible field is not empty.");
                return false;
            }
            else return true;
        }
        -->
    </script>
    <style>
        <!--
        body {
            color: #333;
            background-color: #ddd;
            text-align: center;
            vertical-align: middle;
            font-family: sans-serif;
            font-size: 14px;
        }

        h1 {
            font-family: Courier New, Courier, monospace;
            font-size: 28pt;
        }

        a, a:visited, a:active {
            color: #500;
            text-decoration: none;
        }

            a:hover {
                text-decoration: underline;
            }

        ul, li {
            list-style-type: none;
            list-style-position: inside;
            padding: 0;
            margin: 0;
        }

        #footer {
            right: 0;
            left: 0;
            text-align: center;
            font-family: Courier New, Courier, monospace;
            font-size: 12px;
            padding-bottom: 5px;
            margin-top: 20px;
        }

        #nav {
            list-style-type: none;
            display: inline-block;
            margin: 0 auto;
        }

            #nav li {
                list-style-type: none;
                display: inline-block;
            }

        #header {
            position: relative;
            display: inline-block;
            margin: 0 auto;
            text-align: center;
            width: 60%;
            border-bottom: 1px solid #444;
        }
        -->
    </style>
</head>
<body>
    <div id="header">
        <ul id="nav">
            <li><a href="{% url 'home:index' %}" style="font-size: 18px; font-family: Courier New, Courier, monospace; margin-right: 50px;">Moody Canvas!</a></li>
            <li><a rel="dead placeholder link">Procedure</a> &raquo;</li>
            <li><a href="{% url 'Moody:index' %}">Home</a> &raquo;</li>
            <li><a href="{% url 'Moody:customers' %}">Customers</a>{% if user.is_authenticated %} &raquo;</li>
            <li><a href="{% url 'logout' %}">Logout</a>{% endif %}</li>
        </ul>
    </div>
{% if user.is_authenticated %}
    <h2>Add a Customer</h2>
    {% if cust_exists %}
    <p>{{ cust_exists }} is already in the system.<br />
        <a href="{% url 'Moody:plates' cust_exists %}">Go There.</a><br />
    Or:</p>
    {% endif %}
    <form action="{% url 'Moody:save_new_cust' %}" method="post" onsubmit="return validateName();">
        {% csrf_token %}
        <input placeholder="Enter Customer Name" id="custname" name="custname" type="text" /><br />
        <input type="submit" />
    </form>
{% else %}
    <h2>You are not authorized to make edits to the database.</h2>
{% endif %}
</body>
</html>

MoodyCanvas/Moody/templates/Moody/new_plate.html
<!DOCTYPE html>
<html>
<head>
    <title>Moody Canvas!</title>
    <script type="text/javascript">
        <!--
        function validateInput() {
            var wid = document.getElementById('plate_wid');
            var len = document.getElementById('plate_len');
            var mfr = document.getElementById('plate_mfr');
            var id_no = document.getElementById('plate_id');
            var ser_no = document.getElementById('plate_sn');
            if (wid == '' || len == '' || mfr == '' || id_no == '' || ser_no == '') {
                alert('All fields must be filled.')
            }
            if (wid < 12 || len < 12) {
                alert('This procedure is inappropriate for plates smaller than 12" x 12".')
                return false;
            }
            if (!(mfr)) {
                alert('Plate manufacturer must be non-blank. Enter "Unknown" if there are no markings.')
                return false;
            }

        }
        -->
    </script>
    <style>
        <!--
        body {
            color: #333;
            background-color: #ddd;
            text-align: center;
            vertical-align: middle;
            font-family: sans-serif;
            font-size: 14px;
        }

        h1 {
            font-family: Courier New, Courier, monospace;
            font-size: 28pt;
        }

        a, a:visited, a:active {
            color: #500;
            text-decoration: none;
        }

            a:hover {
                text-decoration: underline;
            }

        ul, li {
            list-style-type: none;
            list-style-position: inside;
            padding: 0;
            margin: 0;
        }

        #footer {
            right: 0;
            left: 0;
            text-align: center;
            font-family: Courier New, Courier, monospace;
            font-size: 12px;
            padding-bottom: 5px;
            margin-top: 20px;
        }

        #nav {
            list-style-type: none;
            display: inline-block;
            margin: 0 auto;
        }

            #nav li {
                list-style-type: none;
                display: inline-block;
            }

        #header {
            position: relative;
            display: inline-block;
            margin: 0 auto;
            text-align: center;
            width: 60%;
            border-bottom: 1px solid #444;
        }
        -->
    </style>
</head>
<body>
    <div id="header">
        <ul id="nav">
            <li><a href="{% url 'home:index' %}" style="font-size: 18px; font-family: Courier New, Courier, monospace; margin-right: 50px;">Moody Canvas!</a></li>
            <li><a rel="dead placeholder link">Procedure</a> &raquo;</li>
            <li><a href="{% url 'Moody:index' %}">Home</a> &raquo;</li>
            <li><a href="{% url 'Moody:customers' %}">Customers</a> &raquo;</li>
            <li><a href="{% url 'Moody:plates' cust %}">Plates</a>{% if user.is_authenticated %} &raquo;</li>
            <li><a href="{% url 'logout' %}">Logout</a>{% endif %}</li>
        </ul>
    </div>
{% if user.is_authenticated %}
    {% if cust %}
    <h2>Add a New Plate for {{ cust }}</h2>
    {% if plate_id %}
    <p class="warning">Plate ID# {{ plate_id }} already exists for this customer.</p>
    {% endif %}
    {% if plate_sn %}
    <p class="warning">A {{ plate_mfr }} with Serial No. {{ plate_sn }} already exists for {{ cust }}.</p>
    {% endif %}
    <form action="{% url 'Moody:save_new_plate' cust %}" method="post" onsubmit="return validateInput();">
        {% csrf_token %}
        <input type="text" id="plate_id" name="plate_id" placeholder="Customer's Plate ID no." /><br />
        <input type="text" id="plate_ser" name="plate_ser" placeholder="Serial Number" /><br />
        <input type="text" id="plate_mfr" name="plate_mfr" placeholder="Manufacturer" /><br />
        <input type="number" id="plate_wid" name="plate_wid" placeholder="Width" /><br />
        <input type="number" id="plate_len" name="plate_len" placeholder="Length" /><br />
        <input type="submit" /><br />
        <span>Width will be saved as the less-long side.</span><br />
    </form>

    {% else %}
    <h1>No Customer Entered</h1>
    <p>
        <a href="{% url 'Moody:new_cust' %}">Add one?</a><br />
        <a href="{% url 'Moody:customers' %}">Browse Customers</a>
    </p>
    {% endif %}
{% else %}
    <h2>You are not authorized to make changes to the database.</h2>
{% endif %}
</body>
</html>

MoodyCanvas/Moody/templates/Moody/plates.html
<!DOCTYPE html>
<html>
<head>
    <title>Moody Canvas!</title>

    <style>
        <!--
        body {
            color: #333;
            background-color: #ddd;
            text-align: center;
            vertical-align: middle;
            font-family: sans-serif;
            font-size: 14px;
        }

        h1 {
            font-family: Courier New, Courier, monospace;
            font-size: 28pt;
        }

        a, a:visited, a:active {
            color: #500;
            text-decoration: none;
        }

            a:hover {
                text-decoration: underline;
            }

        ul, li {
            list-style-type: none;
            list-style-position: inside;
            padding: 0;
            margin: 0;
        }

        #footer {
            right: 0;
            left: 0;
            text-align: center;
            font-family: Courier New, Courier, monospace;
            font-size: 12px;
            padding-bottom: 5px;
            margin-top: 20px;
        }

        #nav {
            list-style-type: none;
            display: inline-block;
            margin: 0 auto;
        }

            #nav li {
                list-style-type: none;
                display: inline-block;
            }

        #header {
            position: relative;
            display: inline-block;
            margin: 0 auto;
            text-align: center;
            width: 60%;
            border-bottom: 1px solid #444;
        }
        -->
    </style>
</head>
<body>
    <div id="header">
        <ul id="nav">
            <li><a href="{% url 'home:index' %}" style="font-size: 18px; font-family: Courier New, Courier, monospace; margin-right: 50px;">Moody Canvas!</a></li>
            <li><a rel="dead placeholder link">Procedure</a> &raquo;</li>
            <li><a href="{% url 'Moody:index' %}">Home</a> &raquo;</li>
            <li><a href="{% url 'Moody:customers' %}">Customers</a>{% if user.is_authenticated %} &raquo;</li>
            <li><a href="{% url 'logout' %}">Logout</a>{% endif %}</li>
        </ul>
    </div>

{% if not plate_list %}
    <h2>No plates for {{ view.kwargs.custname }}.</h2>
    {% if user.is_authenticated %}
    <p><a href="{% url 'Moody:new_plate' view.kwargs.custname %}">Add one</a></p>
    {% endif %}
{% else %}
    <h2>{{ view.kwargs.custname }}'s Plates</h2>
    {% if user.is_authenticated %}
    <p><a href="{% url 'Moody:new_plate' view.kwargs.custname %}">Add a New Plate</a></p>
    {% endif %}
    <ul>
        {% for p in plate_list %}
        <li><a href="{% url 'Moody:verifs' view.kwargs.custname p %}">{{ p }}</a></li>
        {% endfor %}
    </ul>
    {% endif %}
</body>
</html>

MoodyCanvas/Moody/templates/Moody/summary.html
<!DOCTYPE html>
<html>
<head>
    <title>Moody Canvas!</title>

    <style>
        <!--
        body {
            color: #333;
            background-color: #ddd;
            vertical-align: middle;
            text-align: center;
            font-family: sans-serif;
            font-size: 14px;
        }

        a, a:visited, a:active {
            color: #500;
            text-decoration: none;
        }

        a:hover {
            text-decoration: underline;
        }

        ul, li {
            list-style-type: none;
            list-style-position: inside;
            padding: 0;
            margin: 0;
        }

        #footer {
            right: 0;
            left: 0;
            text-align: center;
            font-family: Courier New, Courier, monospace;
            font-size: 12px;
            padding-bottom: 5px;
            margin-top: 20px;
        }

        #profiles {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
        }

        .profile {
            display: inline-block;
            vertical-align: top;
            margin-right: 10px;
        }

        .measurements {
            list-style: none;
            margin: 5px 0;
            padding: 0;
        }

        #nav {
            list-style-type: none;
            display: inline-block;
            margin: 0 auto;
        }

        #nav li {
            list-style-type: none;
            display: inline-block;
        }

        #header {
            position: relative;
            display: inline-block;
            margin: 0 auto;
            text-align: center;
            width: 60%;
            border-bottom: 1px solid #444;
        }
        -->
    </style>
</head>
<body>
    <div id="header">
        <ul id="nav">
            <li><a href="{% url 'home:index' %}" style="font-size: 18px; font-family: Courier New, Courier, monospace; margin-right: 50px;">Moody Canvas!</a></li>
            <li><a rel="dead placeholder link">Procedure</a> &raquo;</li>
            <li><a href="{% url 'Moody:index' %}">Home</a> &raquo;</li>
            <li><a href="{% url 'Moody:customers' %}">Customers</a> &raquo;</li>
            <li><a href="{% url 'Moody:plates' view.kwargs.custname %}">Plates</a> &raquo;</li>
            <li><a href="{% url 'Moody:verifs' view.kwargs.custname view.kwargs.id_no %}">Verifications</a>{% if user.is_authenticated %} &raquo;</li>
            <li><a href="{% url 'logout' %}">Logout</a>{% endif %}</li>
        </ul>
    </div>
    {% if profile_list %}
    <h2>{{ view.kwargs.custname }}: {{ view.kwargs.id_no }} on {{ profile_list.0.verif_id.verif_date.date }} at {{ profile_list.0.verif_id.verif_date.time }}</h2>
    <p>
{% if user.is_authenticated %}
        <a href="{% url 'Moody:new_verif' view.kwargs.custname view.kwargs.id_no %}">Verify Again</a><br /><br />
{% endif %}       
        <a href="{% url 'Moody:canvas' view.kwargs.custname view.kwargs.id_no view.kwargs.ver_id %}">Show Moody Map</a><br />
        <a href="{% url 'Moody:heights' view.kwargs.custname view.kwargs.id_no view.kwargs.ver_id %}">Show Heights Map</a><br />
    </p>
    <h2>Plate Info:</h2>
    <p>
        <div style="display: inline-block; margin-right: 50px;">
            <div style="display: inline-block; margin-right: 10px; text-align: right;">
                <span>Manufacturer: </span><br />
                <span>Serial No.: </span>
            </div>
            <div style="display: inline-block; text-align: left;">
                <span>{{ profile_list.0.verif_id.plate_id.plate_mfr }}</span><br />
                <span>{{ profile_list.0.verif_id.plate_id.plate_sn }}</span>
            </div>
        </div>
        <div style="display: inline-block;">
            <div style="display: inline-block; margin-right: 10px; text-align: right;">
                <span>Width: </span><br />
                <span>Length:</span>
            </div>
            <div style="display: inline-block; text-align: left;">
                <span>{{ profile_list.0.verif_id.plate_id.plate_wid }} in</span><br />
                <span>{{ profile_list.0.verif_id.plate_id.plate_len }} in</span>
            </div>
        </div>
    </p>
    <h2>Verification Info:</h2>

    <p>
        <div style="display: inline-block;">
            <div style="display: inline-block; margin-right: 10px; text-align: right;">
                <span>Certification No.:</span><br />
                <span>Technician:</span><br />
                <span>Reference Line:</span><br />
                <span>Foot Spacing:</span><br />
                <span>Min:</span><br />
                <span>Line 7 Closure Error:</span><br />
                <span>Start Temp:</span><br />
                <span>End Temp:</span>
            </div>
            <div style="display: inline-block; text-align: left;">
                <span>{{ profile_list.0.verif_id.verif_cert }}</span><br />
                <span>{{ profile_list.0.verif_id.verif_tech }}</span><br />
                <span>Line {{ profile_list.0.verif_id.verif_north }}</span><br />
                <span>{{ profile_list.0.verif_id.verif_foot }} in</span><br />
                <span>{{ profile_list.0.verif_id.verif_min }} &micro;in</span><br />
                <span>{{ profile_list.0.verif_id.clos_7 }} &micro;in</span><br />
                <span>{{ profile_list.0.verif_id.verif_start }} &deg;F</span><br />
                <span>{{ profile_list.0.verif_id.verif_end }} &deg;F</span><br />
            </div>
        </div>
        <div style="display: inline-block;">
            <div style="display: inline-block; margin-right: 10px; text-align: right;">
                <span>Run Description:</span><br />
                <span>Top Temp:</span><br />
                <span>Bottom Temp:</span><br />
                <span>Repeat Reading:</span><br />
                <span>Max:</span><br />
                <span>Line 8 Closure Error:</span><br />
                <span>Flatness:</span><br />
                <span>Plate Grade:</span><br />
            </div>
            <div style="display: inline-block; text-align: left;">
                <span>{{ profile_list.0.verif_id.verif_descr }}</span><br />
                <span>{{ profile_list.0.verif_id.verif_bot }} &deg;F</span><br />
                <span>{{ profile_list.0.verif_id.verif_top }} &deg;F</span><br />
                <span>{{ profile_list.0.verif_id.verif_rep }} &micro;in</span><br />
                <span>{{ profile_list.0.verif_id.verif_max }} &micro;in</span><br />
                <span>{{ profile_list.0.verif_id.clos_8 }} &micro;in</span><br />
                <span>{{ profile_list.0.verif_id.verif_flat }} &micro;in</span><br />
                <span>{{ profile_list.0.verif_id.verif_grade }}</span><br />
            </div>
        </div>
    </p>
    <h3>Measurements (&micro;in):</h3>
    <ul id="profiles">
        {% for profile in profile_list %}
        <li class="profile">
            </Dev>Line {{ forloop.counter }}:
            <ul class="measurements">
                {% for meas in profile.meas_set.all %}
                <li>{{ meas.measurement }}</li>
                {% endfor %}
            </ul>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <h2>There is no verification with this ID# for {{ view.kwargs.custname}}'s plate id# {{ view.kwargs.id_no }}</h2>
    {% endif %}
</body>
</html>

MoodyCanvas/Moody/templates/Moody/verifs.html
<!DOCTYPE html>
<html>
<head>
    <title>Moody Canvas!</title>

    <style>
        <!--
        body {
            color: #333;
            background-color: #ddd;
            text-align: center;
            vertical-align: middle;
            font-family: sans-serif;
            font-size: 14px;
        }

        h1 {
            font-family: Courier New, Courier, monospace;
            font-size: 28pt;
        }

        a, a:visited, a:active {
            color: #500;
            text-decoration: none;
        }

            a:hover {
                text-decoration: underline;
            }

        ul, li {
            list-style-type: none;
            list-style-position: inside;
            padding: 0;
            margin: 0;
        }

        #footer {
            right: 0;
            left: 0;
            text-align: center;
            font-family: Courier New, Courier, monospace;
            font-size: 12px;
            padding-bottom: 5px;
            margin-top: 20px;
        }

        #nav {
            list-style-type: none;
            display: inline-block;
            margin: 0 auto;
        }

            #nav li {
                list-style-type: none;
                display: inline-block;
            }

        #header {
            position: relative;
            display: inline-block;
            margin: 0 auto;
            text-align: center;
            width: 60%;
            border-bottom: 1px solid #444;
        }
        -->
    </style>
</head>
<body>
    <div id="header">
        <ul id="nav">
            <li><a href="{% url 'home:index' %}" style="font-size: 18px; font-family: Courier New, Courier, monospace; margin-right: 50px;">Moody Canvas!</a></li>
            <li><a rel="dead placeholder link">Procedure</a> &raquo;</li>
            <li><a href="{% url 'Moody:index' %}">Home</a> &raquo;</li>
            <li><a href="{% url 'Moody:customers' %}">Customers</a> &raquo;</li>
            <li><a href="{% url 'Moody:plates' view.kwargs.custname %}">Plates</a>{% if user.is_authenticated %} &raquo;</li>
            <li><a href="{% url 'logout' %}">Logout</a>{% endif %}</li>
        </ul>
    </div>
    <h2>{{ view.kwargs.custname }} - {{ view.kwargs.id_no }}</h2>
{% if not recent_verifs %}
    <h2>No verifications on this plate.</h2>
    {% if user.is_authenticated %}
    <p><a href="{% url 'Moody:new_verif' view.kwargs.custname view.kwargs.id_no %}">Verify This Plate Now</a></p>
    {% endif %}
{% else %}
    {% if user.is_authenticated %}
    <p><a href="{% url 'Moody:new_verif' view.kwargs.custname view.kwargs.id_no %}">Verify This Plate Now</a></p>
    {% endif %}
    <p>{{ recent_verifs.0.plate_id.plate_mfr }}, sn {{ recent_verifs.0.plate_id.plate_sn }}<br />{{ recent_verifs.0.plate_id.plate_wid }} in x {{ recent_verifs.0.plate_id.plate_len }} in</p>
    <ul>
        {% for v in recent_verifs %}
        <li><a href="{% url 'Moody:summary' view.kwargs.custname view.kwargs.id_no v.id %}">{{ v }}: {{ v.verif_descr }}</a></li>
        {% endfor %}
    </ul>
    {% endif %}
</body>
</html>